# CoreProtectの設定

# CoreProtectはドネーションウェアです。寄付キーは、coreprotect.net/donate/から入手してください。
donation-key: 

# MySQLはオプションであり、必須ではありません。
# もしMySQLを使いたい場合は、以下を有効にして、フィールドに記入してください。
use-mysql: false
table-prefix: co_
mysql-host: 127.0.0.1
mysql-port: 3306
mysql-database: database
mysql-username: root
mysql-password: 

# 変更された場合, 自動的に言語フレーズの翻訳を試みます.
# 言語コードのリスト: https://coreprotect.net/languages/
# ここでjaを入力すると自動翻訳されますが精度がとても低いので非推奨です。
language: en

# 有効化された場合、CoreProtectはサーバの起動時にアップデートの有無を確認します。
# アップデートが利用可能な場合, サーバコンソールから通知が行われます.
check-updates: true

# 有効にすると、他のプラグインがCoreProtect APIを利用することができるようになります。
api-enabled: true

# 有効にすると、ロールバックやリストアの際に余計なデータが表示される。
# ロールバックコマンドに "#verbose" を追加することで、手動で起動することもできます。
verbose: true

# ロールバックやリストアで半径が指定されない場合、この値が半径として使用されます。
# 半径として使用されます。半径を自動的に追加しないようにするには, "0 "を設定します.
default-radius: 10

# コマンドで使用できる最大半径を指定します。無効にするには "0 "を設定する。
# 半径を指定せずにロールバックやリストアを実行するには, "r:#global "を利用することができます.
max-radius: 100

# 有効にすると、コンテナ(など)から取り出したアイテムもロールバックに含まれるようになります。
rollback-items: true

# 有効化された場合、殺された動物などの実体がロールバックに含まれるようになります。
rollback-entities: true

# 有効にすると、ゾンビが昼間に燃えているような一般的なデータは記録されません。
skip-generic-data: true

# プレイヤーによって配置されたブロックを記録します。
block-place: true

# プレイヤーによって壊されたブロックを記録します。
block-break: true

# 他のブロックから壊れる丸太のブロック。例えば、看板や松明など。
# プレーヤーが壊した土のブロックから落ちる。これは
# ベッドやドアを適切にロールバックさせるために必要です.
natural-break: true

# 砂や砂利の落下など、ブロックの動きを適切に追跡する。
block-movement: true

# ピストンで動かされるブロックを適切に追跡する。
pistons: true

#火事で燃え尽きる丸太ブロック。
block-burn: true

# 延焼によりブロックが自然に発火した場合のログ。
block-ignite: true

# TNT や Creepers などの爆発を記録します。
explosions: true

# エンダーマンがブロックを破壊するような、エンティティがブロックを変更するときを追跡する。
entity-change: true

# 殺された牛やエンダーマンのような殺された実体のログを取得します.
entity-kills: true

# 看板のテキストを記録します。無効化された場合、ロールバックされたときに標識は空白になる。
sign-text: true

# バケツを使っているプレイヤーが溶岩や水源を設置・撤去したログを記録します。
buckets: true

# Logs 自然の木の葉の腐敗。
leaf-decay: true

# 木の成長を記録する。木は、サップリングを植えたプレイヤーにリンクされている。
tree-growth: true

# キノコの成長を記録します。
mushroom-growth: true

# 自然の蔓の成長を記録する。
vine-growth: true

# sculk触媒からsculkブロックの拡散を記録します。
sculk-spread: true

# ネザーポータルのようなポータルが自然に生成されるときのログを記録します。
portals: true

# 水の流れを記録します。水がトーチなどの他のブロックを破壊した場合,
# これで適切にロールバックすることができる。
water-flow: true

# 溶岩の流れを記録する。溶岩がトーチのような他のブロックを破壊した場合,
# これで適切にロールバックさせることができる。
lava-flow: true

# 液体を適切に追跡し、プレイヤーにリンクさせることができるようになります。
# 例えば、あるプレイヤーが水を配置し、それが流れて松明を破壊した場合。
# その一人のプレイヤーをロールバックさせることで、全てを適切に復元することができます。
liquid-tracking: true

# チェストやファーネス、ディスペンサーからプレイヤーがアイテムを取り出した時など、アイテムの取引を記録します。
# チェスト、ファーネス、ディスペンサーからアイテムを取るときなど、アイテムの取引を記録します。
item-transactions: true

# プレイヤーによって落とされたアイテムのログを記録します。
item-drops: true

# プレーヤーが拾ったアイテムのログを記録します。
item-pickups: true

# ホッパーから物品が取り除かれたときなど、すべてのホッパートランザクションを追跡する。
# チェスト、ファーネス、ディスペンサー
hopper-transactions: true

# プレイヤーがドアを開ける、ボタンを押す、チェストを開けるなどのインタラクションを記録します。
#ボタンを押したとき、またはチェストを開けたときのような、プレイヤーとのインタラクションをトラッキングします。プレイヤーのインタラクションをロールバックすることはできません.
player-interactions: true

# チャットでプレイヤーが送信したメッセージを記録します。
player-messages: true

# プレイヤーによって使われた全てのコマンドのログを記録します.
player-commands: true

# プレイヤーのログインとログアウトを記録します.
player-sessions: true

# プレイヤーが Minecraft のユーザー名を変更したときにログを記録します。
username-changes: true

# あなたのサーバーでプラグイン "WorldEdit "が利用されている場合、それを経由して行われた変更を記録します。
worldedit: true
